GET http://localhost:3000/projects


###
# @name createProject
POST http://localhost:3000/projects
Content-Type: application/json

{
    "name": "Project 1",
    "description": "Description 1"
}

###
@project_id = {{createProject.response.body.id}}

###
POST http://localhost:3000/projects/{{project_id}}/start
Content-Type: application/json

{
    "started_at": "2020-01-01"
}
